import { FC } from "react"
import Head from 'next/head'
import styles from './MainLayout.module.css'
import { NavBar } from "../Navbar"

interface Props {
    children?: React.ReactNode | undefined
}

export const MainLayout: FC<Props> = ({ children }) => {
    return (
        <div className={styles.container}>

        <Head>
            <title> Home </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />

        <main className={styles.main}>
            
            { children }

        </main>

        </div>
    )
}
